config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index,:new, :create, :destroy]
  resources :gifts do
    resources :purchases, only: [:new, :create]
  end

  root 'gifts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gift.rb
class Gift < ApplicationRecord
  has_one_attached :image

  scope :pixes , -> { where(name: "pix").first }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  def admin?
    true if admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  # Confirms a logged-in user.
  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to login_url # halts request cycle
    end
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :require_login, except: [:index]
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @gifts = Gift.all
  end

  def show
    @gift = Gift.find(params[:id])
  end
  def new
    @gift = Gift.new
  end

  def create
    @gift = Gift.new(gift_params)

    if @gift.save
      redirect_to gifts_path
    else
      render :new
    end
  end

  def edit
    @gift = Gift.find(params[:id])
  end

  def update
    @gift = Gift.find(params[:id])

    if @gift.update(gift_params)
      redirect_to gifts_path
    else
      render :edit
    end
  end

  def destroy
    @gift = Gift.find(params[:id])
    @gift.destroy

    redirect_to gifts_path
  end

  private

  def gift_params
    params.require(:gift).permit(:name, :link, :image, :price)
  end

  def require_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new', status: :unauthorized
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController

  def index
    @users = User.all
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Account successfully created"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then 'alert alert-success'
    when 'alert' then 'alert alert-danger'
    end
  end

  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, class: class_name) do
      link_to link_text, link_path
    end
  end
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/gifts/edit.html.erb
<h1>Edit Gift Idea</h1>
<%= form_with model: @gift do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>
  <div>
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <%= form.submit %>
<% end %>

app/views/gifts/new.html.erb
<h1>New Gift Idea</h1>
<%= form_with model: @gift do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>
  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <%= form.submit %>
<% end %>

app/views/gifts/show.html.erb
<!-- generate the show html.erb using the gifts_controller#show as base -->
<h1>
  <%= @gift.name %>
</h1>
<p>
  <strong>Price:</strong>
  <%= @gift.price %>
</p>

<p>
  <strong>Link:</strong>
  <%= @gift.link %>
</p>

<p>
  <strong>Image:</strong>
  <%= @gift.image %>
</p>

<p>
  <strong>PIX</strong>
  <%= image_tag @pix_qrcode %>
</p>

<!-- add a link to the edit page -->
<%= link_to 'Edit', edit_gift_path(@gift) %> |

<!-- add a link to the index page -->
<%= link_to 'Back', gifts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GiftIdeas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_with model: @user, url: user_path(@user), method: :put do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password_digest %>
    <%= form.password_field :password_digest %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Delete', user_path(user), data: { turbo_confirm: 'Are you sure?', turbo_method: "delete" } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_with model: @user, url: users_path do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>
  <div>
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>